{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) (include "maxkb.needsSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maxkb.secretName" . }}
  labels:
    {{- include "maxkb.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if and .Values.database.external.enabled .Values.database.external.password }}
  MAXKB_DB_PASSWORD: {{ .Values.database.external.password | quote }}
  {{- end }}
  {{- if and .Values.redis.external.enabled .Values.redis.external.password }}
  MAXKB_REDIS_PASSWORD: {{ .Values.redis.external.password | quote }}
  {{- end }}
{{- end }}
