{{- $ctx := . -}}
{{- if .Values.auth.enabled }}
{{- if not .Values.auth.existingSecret }}
{{- range .Values.registries }}
{{- if include "docker-proxy.authEnabled" (dict "ctx" $ctx "reg" .) }}
{{- $name := include "docker-proxy.registryName" (dict "ctx" $ctx "reg" .) }}
{{- $entries := list }}
{{- range $ctx.Values.auth.users }}
{{- $entries = append $entries (htpasswd .username .password) }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docker-proxy.authSecretName" (dict "ctx" $ctx "reg" .) }}
  labels:
    {{- include "docker-proxy.registryLabels" (dict "ctx" $ctx "reg" .) | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
{{ join "\n" $entries | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
